[project]
name = "trinitron"
version = "0.1.0"
description = "Filter an image to look like a photo of a Sony Trinitron CRT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.1.0",
]
